modLoader = "javafml"
loaderVersion = "[1,)"
#issueTrackerURL = "A valid URL to your issue tracker where people can open bug tickets"
license = "All Rights Reserved"

[[mods]]
modId = "cobblemongenerationspawns"
version = "${version}"
displayName = "Cobblemon: Generation Waves"
authors = "DAN2026"
description = '''
A Cobblemon Side Mod that allows you to enable / disable certain generations from spawning.
'''

[[dependencies.cobblemongenerationspawns]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.cobblemongenerationspawns]]
modId = "neoforge"
mandatory = true
versionRange = "[21.1.182,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cobblemongenerationspawns]]
modId = "cobblemon"
mandatory = true
versionRange = "[1.7.3,)"
ordering = "AFTER"
side = "BOTH"
